/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author CHRISTIAN
 */
public class projectsForm extends javax.swing.JFrame {

private static final Logger logger = Logger.getLogger(ProjectFormAD.class.getName());

    public projectsForm() {
        initComponents();
        
         displayData(); 
    }
      public void displayData() {
    try {
        dbConnector dbc = new dbConnector();    
        ResultSet rs = dbc.getData("SELECT p_id, project_name, description, status, due_date FROM tbl_projects");
        projectTable.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
        logger.info("Displayed project data successfully.");
    } catch (SQLException ex) {
        logger.log(Level.SEVERE, "Error displaying project data: " + ex.getMessage(), ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();
        t_add = new javax.swing.JPanel();
        acc_name = new javax.swing.JLabel();
        t_update = new javax.swing.JPanel();
        acc_name2 = new javax.swing.JLabel();
        t_delete = new javax.swing.JPanel();
        acc_name3 = new javax.swing.JLabel();
        acc_name1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        projectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(projectTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 520, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrator (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        acc_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acc_id.setText("  ID");
        jPanel1.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 30, 30));

        t_add.setBackground(new java.awt.Color(42, 59, 159));
        t_add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_addMouseExited(evt);
            }
        });
        t_add.setLayout(null);

        acc_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name.setText("ADD");
        acc_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        t_add.add(acc_name);
        acc_name.setBounds(50, 10, 40, 20);

        jPanel1.add(t_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 40));

        t_update.setBackground(new java.awt.Color(42, 59, 159));
        t_update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_updateMouseExited(evt);
            }
        });
        t_update.setLayout(null);

        acc_name2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name2.setText("EDIT");
        acc_name2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        t_update.add(acc_name2);
        acc_name2.setBounds(50, 10, 40, 20);

        jPanel1.add(t_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 40));

        t_delete.setBackground(new java.awt.Color(42, 59, 159));
        t_delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_deleteMouseExited(evt);
            }
        });
        t_delete.setLayout(null);

        acc_name3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name3.setText("DELETE");
        acc_name3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        t_delete.add(acc_name3);
        acc_name3.setBounds(40, 10, 70, 20);

        jPanel1.add(t_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 40));

        acc_name1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name1.setText("Current User");
        acc_name1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(acc_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        jPanel3.setBackground(new java.awt.Color(12, 226, 240));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel1.setText("Projects Form");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(286, 286, 286))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        adminDashboard adb = new adminDashboard();
        adb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void t_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_addMouseClicked
         logger.info("Navigating to add project form.");
        ProjectFormAD pad = new ProjectFormAD();
        pad.setVisible(true);
        pad.ts.setEnabled(false); 
        new dbConnector().logAction(Session.getInstance().getUid(), "Navigated to add project form.");

    }//GEN-LAST:event_t_addMouseClicked

    private void t_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_addMouseEntered

        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_add.setBackground(hovercolor);
    }//GEN-LAST:event_t_addMouseEntered

    private void t_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_addMouseExited
        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_add.setBackground(navcolor);
    }//GEN-LAST:event_t_addMouseExited

    private void t_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_updateMouseClicked
          logger.info("Navigating to update project form.");
            int rowIndex = projectTable.getSelectedRow();

    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please select a project to update!");
        logger.warning("No project selected for update.");
    } else {
        try {
            dbConnector dbc = new dbConnector();
            TableModel tbl = projectTable.getModel();
            String projectId = tbl.getValueAt(rowIndex, 0).toString(); // p_id
            ResultSet rs = dbc.getData("SELECT * FROM tbl_projects WHERE p_id = '" + projectId + "'");

            if (rs.next()) {
                // Create an instance of ProjectFormAD to populate fields
                ProjectFormAD pf = new ProjectFormAD();
                pf.pn.setText(rs.getString("project_name"));
                pf.pd.setText(rs.getString("description")); // If you want this
                pf.dd.setText(rs.getString("due_date"));
                pf.ts.setSelectedItem(rs.getString("status"));
                pf.tid.setText(rs.getString("t_id")); // Task ID
                pf.uid.setText(rs.getString("u_id")); // User ID

                pf.setVisible(true);
                this.dispose(); // Close the current form

                dbc.logAction(Session.getInstance().getUid(), "Navigated to update project form for project ID: " + projectId);
            }
            rs.close();
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Error fetching data for project update: " + ex.getMessage(), ex);
        }
    }
    }//GEN-LAST:event_t_updateMouseClicked

    private void t_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_updateMouseEntered
        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_update.setBackground(hovercolor);
    }//GEN-LAST:event_t_updateMouseEntered

    private void t_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_updateMouseExited
        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_update.setBackground(navcolor);
    }//GEN-LAST:event_t_updateMouseExited

    private void t_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_deleteMouseClicked
         int rowIndex = projectTable.getSelectedRow();
    logger.info("Attempting to delete a project.");

    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please select a project to delete!");
    } else {
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this project?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            TableModel tbl = projectTable.getModel();
            String id = tbl.getValueAt(rowIndex, 0).toString(); // p_id column

            dbConnector dbc = new dbConnector();
            try {
                boolean isDeleted = dbc.deleteProjectById(id); // Call your delete method

                if (isDeleted) {
                    dbc.logAction(Session.getInstance().getUid(), "Deleted project with ID " + id);
                    JOptionPane.showMessageDialog(null, "Project deleted successfully.");
                    displayData(); // Refresh the project data
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to delete project.");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_t_deleteMouseClicked

    private void t_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_deleteMouseEntered

        Color hovercolor = new Color(51,126,159);

        t_delete.setBackground(hovercolor);
    }//GEN-LAST:event_t_deleteMouseEntered

    private void t_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_deleteMouseExited
        Color navcolor = new Color(42,59,159);

        t_delete.setBackground(navcolor);
    }//GEN-LAST:event_t_deleteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projectsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projectsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel acc_name1;
    private javax.swing.JLabel acc_name2;
    private javax.swing.JLabel acc_name3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable projectTable;
    private javax.swing.JPanel t_add;
    private javax.swing.JPanel t_delete;
    private javax.swing.JPanel t_update;
    // End of variables declaration//GEN-END:variables
}
