
package admin;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class tasksForm extends javax.swing.JFrame {
        private static final Logger logger = Logger.getLogger(tasksForm.class.getName());
        private javax.swing.JTable tasksTable;
    public tasksForm() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        int frameWidth = 690;
        int frameHeight = 442;

        int centerX = (screenWidth - frameWidth) / 2;
        int centerY = (screenHeight - frameHeight) / 2;

        setBounds(centerX, centerY, frameWidth, frameHeight);
        setResizable(false);

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent e) {
                setLocation(centerX, centerY); 
            }
        });

        displayData(); 
    }
     public void displayData() {
        try {
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT title, description, status, due_date FROM tbl_task");
            taskTable.setModel(DbUtils.resultSetToTableModel(rs)); 
            rs.close();
            logger.info("Displayed task data successfully.");
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, "Error displaying task data: " + ex.getMessage(), ex);
        } 
    }



   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();
        t_add = new javax.swing.JPanel();
        acc_name = new javax.swing.JLabel();
        t_update = new javax.swing.JPanel();
        acc_name2 = new javax.swing.JLabel();
        t_delete = new javax.swing.JPanel();
        acc_name3 = new javax.swing.JLabel();
        acc_name1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(taskTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 520, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrator (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        acc_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acc_id.setText("  ID");
        jPanel1.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 30, 30));

        t_add.setBackground(new java.awt.Color(42, 59, 159));
        t_add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_addMouseExited(evt);
            }
        });
        t_add.setLayout(null);

        acc_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name.setText("ADD");
        acc_name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        t_add.add(acc_name);
        acc_name.setBounds(50, 10, 40, 20);

        jPanel1.add(t_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 40));

        t_update.setBackground(new java.awt.Color(42, 59, 159));
        t_update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_updateMouseExited(evt);
            }
        });
        t_update.setLayout(null);

        acc_name2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name2.setText("EDIT");
        acc_name2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        t_update.add(acc_name2);
        acc_name2.setBounds(50, 10, 40, 20);

        jPanel1.add(t_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 40));

        t_delete.setBackground(new java.awt.Color(42, 59, 159));
        t_delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        t_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_deleteMouseExited(evt);
            }
        });
        t_delete.setLayout(null);

        acc_name3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name3.setText("DELETE");
        acc_name3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        t_delete.add(acc_name3);
        acc_name3.setBounds(40, 10, 70, 20);

        jPanel1.add(t_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 40));

        acc_name1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        acc_name1.setText("Current User");
        acc_name1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(acc_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        jPanel3.setBackground(new java.awt.Color(12, 226, 240));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        jLabel1.setText("TASKS FORM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel1)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        adminDashboard adb = new adminDashboard();
        adb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void t_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_addMouseClicked
        logger.info("Navigating to add task form.");
       taskFormAD tad = new taskFormAD();
    tad.setVisible(true);
    tad.ts.setEnabled(false);
    new dbConnector().logAction(Session.getInstance().getUid(), "Navigated to add user form.");
    }//GEN-LAST:event_t_addMouseClicked

    private void t_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_addMouseEntered

        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_add.setBackground(hovercolor);
    }//GEN-LAST:event_t_addMouseEntered

    private void t_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_addMouseExited
        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_add.setBackground(navcolor);
    }//GEN-LAST:event_t_addMouseExited

    private void t_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_updateMouseClicked
        logger.info("Navigating to update task form.");
        int rowIndex = taskTable.getSelectedRow();

if (rowIndex < 0) {
    JOptionPane.showMessageDialog(null, "Please select a task to update!");
    logger.warning("No task selected for update.");
} else {
    try {
        dbConnector dbc = new dbConnector();
        TableModel tbl = tasksTable.getModel();
        ResultSet rs = dbc.getData("SELECT * FROM tbl_tasks WHERE t_id = '" + tbl.getValueAt(rowIndex, 0) + "'");

        if (rs.next()) {
            taskFormAD tf = new taskFormAD(); 
            tf.uid.setText(String.valueOf(rs.getInt("t_id"))); 
            tf.tn.setText(rs.getString("title"));
            tf.td.setText(rs.getString("description"));
            tf.dd.setText(rs.getString("due_date"));
            tf.ts.setSelectedItem(rs.getString("status")); 
           
            
            tf.add.setEnabled(false);
            tf.update.setEnabled(true); 

            tf.setVisible(true);
            this.dispose(); 
            
            dbc.logAction(Session.getInstance().getUid(), "Navigated to update task form for task ID: " + rs.getInt("t_id"));
        }
    } catch (SQLException ex) {
        logger.log(Level.SEVERE, "Error fetching data for task update: " + ex.getMessage(), ex);
    }
}
    }//GEN-LAST:event_t_updateMouseClicked

    private void t_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_updateMouseEntered
        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_update.setBackground(hovercolor);
    }//GEN-LAST:event_t_updateMouseEntered

    private void t_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_updateMouseExited
        Color navcolor = new Color(42,59,159);
        Color hovercolor = new Color(51,126,159);

        t_update.setBackground(navcolor);
    }//GEN-LAST:event_t_updateMouseExited

    private void t_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_deleteMouseClicked
      int rowIndex = tasksTable.getSelectedRow();
    logger.info("Navigating to delete a task from the form.");
    if (rowIndex < 0) {
    JOptionPane.showMessageDialog(null, "Please select a task to delete!");
    } else {
    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this task?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        TableModel tbl = tasksTable.getModel();
        String id = tbl.getValueAt(rowIndex, 0).toString(); // Assuming the first column is the task ID

        dbConnector dbc = new dbConnector();
        try {
            boolean isDeleted = dbc.deleteTaskById(id); // Assuming you have this method in your dbConnector

            if (isDeleted) {
                dbc.logAction(Session.getInstance().getUid(), "Deleted task with ID " + id); // Log deletion
                JOptionPane.showMessageDialog(null, "Task deleted successfully.");
                displayData(); // Refresh the task list
            } else {
                JOptionPane.showMessageDialog(null, "Failed to delete task.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }
}
    }//GEN-LAST:event_t_deleteMouseClicked

    private void t_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_deleteMouseEntered

        Color hovercolor = new Color(51,126,159);

        t_delete.setBackground(hovercolor);
    }//GEN-LAST:event_t_deleteMouseEntered

    private void t_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_deleteMouseExited
        Color navcolor = new Color(42,59,159);

        t_delete.setBackground(navcolor);
    }//GEN-LAST:event_t_deleteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tasksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tasksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tasksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tasksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tasksForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel acc_name1;
    private javax.swing.JLabel acc_name2;
    private javax.swing.JLabel acc_name3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel t_add;
    private javax.swing.JPanel t_delete;
    private javax.swing.JPanel t_update;
    private javax.swing.JTable taskTable;
    // End of variables declaration//GEN-END:variables
}
